Repository canonical/github-runner-image-builder-operator, pull requests merged in 2024-11, with the labels that each got.

#40 chore: refactor cos & minor changes
  src/charm.py
  src/cos.py
  tests/integration/test_charm.py
  tests/unit/test_state.py
Labels: Libraries: Out of sync, trivial

#41 Add workflow to auto approve bot PRs
  .github/workflows/bot_pr_approval.yaml
Labels: Libraries: Out of sync, trivial

#45 feat: script url config
  charmcraft.yaml
  src-docs/builder.py.md
  src-docs/state.py.md
  src/builder.py
  src/state.py
  tests/unit/factories.py
  tests/unit/test_builder.py
  tests/unit/test_charm.py
  tests/unit/test_state.py
Labels: Libraries: Out of sync, trivial

#47 fix: cron newline
  src/builder.py
  tests/unit/test_builder.py
Labels: bug, Libraries: Out of sync, trivial

#46 chore: refactor datastructs
  src-docs/builder.py.md
  src-docs/charm.py.md
  src-docs/exceptions.py.md
  src-docs/image.py.md
  src-docs/proxy.py.md
  src-docs/state.py.md
  src/builder.py
  src/charm.py
  src/exceptions.py
  src/image.py
  src/proxy.py
  src/state.py
  tests/integration/helpers.py
  tests/unit/factories.py
  tests/unit/test_builder.py
  tests/unit/test_charm.py
  tests/unit/test_image.py
  tests/unit/test_proxy.py
  tests/unit/test_state.py
Labels: complex, Libraries: Out of sync, senior-review-required, refactor

#51 feat: external script secrets
  charmcraft.yaml
  src-docs/builder.py.md
  src-docs/charm.py.md
  src-docs/image.py.md
  src-docs/state.py.md
  src/builder.py
  src/charm.py
  src/image.py
  src/state.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/factories.py
  tests/unit/test_builder.py
  tests/unit/test_state.py
Labels: enhancement, Libraries: Out of sync, senior-review-required
