Repository canonical/github-runner-image-builder-operator, pull requests merged in 2025-03, with the labels that each got.

#88 Fix: move external script secret out of cloud-init
  RELEASE-NOTES.md
  app/src/github_runner_image_builder/errors.py
  app/src/github_runner_image_builder/openstack_builder.py
  app/src/github_runner_image_builder/templates/cloud-init.sh.j2
  app/tests/integration/commands.py
  app/tests/integration/helpers.py
  app/tests/integration/test_openstack_builder.py
  app/tests/unit/test_openstack_builder.py
Labels: bug, Libraries: Out of sync, senior-review-required

#91 Feature: Add focal support
  .github/workflows/integration_test_app.yaml
  RELEASE-NOTES.md
  app/src/github_runner_image_builder/config.py
  app/src/github_runner_image_builder/openstack_builder.py
  app/src/github_runner_image_builder/templates/cloud-init.sh.j2
  app/tests/integration/helpers.py
  app/tests/integration/test_openstack_builder.py
  app/tests/unit/test_config.py
  app/tests/unit/test_openstack_builder.py
  charmcraft.yaml
  docs/how-to/configure-base-image.md
  src/state.py
  tests/unit/test_builder.py
  tests/unit/test_state.py
Labels: Libraries: Out of sync

#95 Terraform charm for the image-builder
  terraform/.gitignore
  terraform/charm/README.md
  terraform/charm/main.tf
  terraform/charm/outputs.tf
  terraform/charm/variables.tf
  terraform/charm/versions.tf
Labels: documentation, Libraries: Out of sync, trivial

#96 Always install aproxy as it could be needed for the runner even if not needed in the builder
  app/src/github_runner_image_builder/config.py
  app/src/github_runner_image_builder/templates/cloud-init.sh.j2
  app/tests/unit/test_openstack_builder.py
Labels: Libraries: Out of sync, trivial
