Repository canonical/github-runner-image-builder-operator, pull requests merged in 2025-04, with the labels that each got.

#101 feat: ppc64le images
  .github/workflows/integration_test_app.yaml
  .github/workflows/promote_charm.yaml
  RELEASE-NOTES.md
  app/src/github_runner_image_builder/cli.py
  app/src/github_runner_image_builder/cloud_image.py
  app/src/github_runner_image_builder/config.py
  app/src/github_runner_image_builder/openstack_builder.py
  app/tests/conftest.py
  app/tests/integration/conftest.py
  app/tests/unit/test_cli.py
  app/tests/unit/test_cloud_image.py
  app/tests/unit/test_config.py
  app/tests/unit/test_openstack_builder.py
  charmcraft.yaml
  src/state.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/test_state.py
Labels: Libraries: Out of sync, trivial

#105 chore: renovate group:allNonMajor
  renovate.json
Labels: Libraries: Out of sync, trivial

#109 chore: reset openstackstdk to upstream
  app/requirements.txt
Labels: Libraries: Out of sync, trivial

#111 fix: image builder doc link in charmcraft.yaml
  charmcraft.yaml
Labels: bug, documentation, Libraries: Out of sync

#113 fix: skip run if relation data is not ready
  app/src/github_runner_image_builder/openstack_builder.py
  docs/changelog.md
  docs/explanation/charm-architecture.md
  src/charm.py
  tests/unit/test_charm.py
Labels: bug, Libraries: Out of sync, trivial
