Repository canonical/github-runner-image-builder-operator, pull requests merged in 2025-06, with the labels that each got.

#121 Feat: reuse image id on relation changed
  CODEOWNERS
  docs/changelog.md
  src/builder.py
  src/charm.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/test_builder.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, senior-review-required

#122 docs: Fix vale style warnings
  .github/workflows/test.yaml
  docs/changelog.md
  docs/index.md
  docs/tutorial/quick-start.md
Labels: documentation, Libraries: Out of sync

#124 feat: log timestamp
  .gitignore
  app/src/github_runner_image_builder/logging.py
  app/tests/integration/conftest.py
  app/tests/unit/test_cli.py
  app/tests/unit/test_logging.py
  src/charm.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
Labels: Libraries: Out of sync, trivial

#125 Chore/refactor os cloud
  app/pyproject.toml
  app/src/github_runner_image_builder/cli.py
  app/tests/unit/test_cli.py
  src/builder.py
  tests/unit/test_builder.py
Labels: Libraries: Out of sync, trivial

#126 fix: click case insensitive
  app/requirements.txt
  app/src/github_runner_image_builder/cli.py
  app/tests/unit/test_cli.py
Labels: bug, Libraries: Out of sync, trivial
